import type { Metadata } from 'next';
import React from 'react';

import '@/styles/globals.css';

import { localPoppins } from '@/constants/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={localPoppins.className}>{children}</body>
    </html>
  );
}
